server_endpoint = "/run/user/1000/clipcat/grpc.sock"
finder = "dmenu"

[rofi]
line_length = 100
menu_length = 30
menu_prompt = "Clipcat"
extra_arguments = []

[dmenu]
line_length = 100
menu_length = 30
menu_prompt = "Select"
extra_arguments = [ "-nf", "white", "-nb", "black", "-sf", "black", "-sb", "white" ]

[custom_finder]
program = "fzf"
args = []

[log]
emit_journald = false
emit_stdout = true
emit_stderr = false
level = "INFO"
