daemonize = true
pid_file = "/run/user/1000/clipcatd.pid"
max_history = 500
history_file_path = "/home/jons/.cache/clipcat/clipcatd-history"
snippets = []

[log]
emit_journald = false
emit_stdout = true
emit_stderr = false
level = "INFO"

[watcher]
load_current = true
enable_clipboard = true
enable_primary = false
enable_secondary = false
sensitive_x11_atoms = ["x-kde-passwordManagerHint"]
filter_text_min_length = 1
filter_text_max_length = 20000000
denied_text_regex_patterns = []
capture_image = true
filter_image_max_size = 5242880

[grpc]
enable_http = true
enable_local_socket = true
host = "127.0.0.1"
port = 45045
local_socket = "/run/user/1000/clipcat/grpc.sock"

[desktop_notification]
enable = true
icon = "accessories-clipboard"
timeout_ms = 5000
long_plaintext_length = 2000
